[site]
base_url = "https://jonathanconde.ch"
title = "conde"
author = "Jonathan Conde"

[assets]
; CSS / JS: Options possibles : inline ou file
css_mode = "inline"
js_mode = "inline"

[features]
generate_categories = "true"
generate_search = "true"

[ignore]
; Liste des fichiers à ne jamais compiler (séparés par un espace ou virgule)
ignore_files = "draft.md secret.php"

[syndication]
; Activer ou désactiver la génération des fichiers (true ou false)
generate_sitemap = "true"
generate_rss = "true"

[seo]
; Exclure tout un dossier du sitemap (true/false)
exclude_categories_from_sitemap = "true"
