[site]
base_url = "https://example.com"
lang = "en"
title = "Susie"
author = "Susie User"
email = "hello@example.com"

[assets]
; Asset loading strategy. Options: "inline" or "file"
css_mode = "inline"
js_mode = "inline"

[features]
generate_categories = "false"
generate_search = "true"

[ignore]
; Space or comma-separated list of filenames to exclude from compilation
ignore_files = "draft.md secret.php"

[syndication]
; Toggles automated generation of discovery files (true or false)
generate_sitemap = "true"
generate_rss = "true"

[seo]
; Option to exclude the category compilation directories from the sitemap (true/false)
exclude_categories_from_sitemap = "true"

[mastodon]
; Configuration for federated comments and footer social links
id = "username"
instance = "mastodon.social"

[social]
; Optional profiles (leave empty or remove to hide from the footer)
linkedin = "https://www.linkedin.com/in/username"
